# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ChinoTseven's Blog
email: cosmo.insane@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    This blog is mainly for self-education and a kind of personal notes 
    on coding tricks.
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Efrain_T
github_username:  elchinot7

# Build settings
markdown: kramdown
